### ISSUE TITLE
Not showing in Lovelace

### ISSUE THREAD

**Issue by filmgarage** [badguy99/PlantPictureCard#1]
I installed this as a module:

```
  - type: module
    url: /hacsfiles/PlantPictureCard/PlantPictureCard.js
```

The option of this custom card shows up when selecting a new card, but it does not show in the interface and keeps the whole dashboard from loading...

This is the setup for the card:

```
type: 'custom:plant-picture-card'
entity: plant.monstera
title: Monstera
image: local/monstera.jpg
```

**Comment by badguy99** [comment]
I think you'd need a '/' before the 'local' on the image line.
Are your images in /config/www/ ? 

e.g.
```
entity: plant.aloe_zebrina
image: /local/AloeZebra.jpg
title: Zebra Aloe Danyz
type: 'custom:plant-picture-card'

entity: plant.sedum_morganianum
image: /local/Sedum.jpg
title: Burro's Tail
type: 'custom:plant-picture-card'
```


```
www $ ls -altr
-rw-r--r--    1 root     root         74264 Jun  7 20:33 AloeZebra.jpg
-rw-r--r--    1 root     root         84313 Jun  7 20:34 Sedum.jpg
-rw-r--r--    1 root     root         65178 Jun  7 20:34 SpiralCacti.jpg
drwxr-xr-x   11 root     root          4096 Jun 21 21:26 community
drwxrwxrwx    3 root     root          4096 Jun 21 21:53 .
drwxr-xr-x   15 root     root          4096 Jun 21 21:53 ..
www $ pwd
/config/www
```

Do you see any messages in the web developer tools in your browser? Any thing in the console section?

**Comment by filmgarage** [comment]
So sorry, that was a typo. I have indeed included the '/'.
Images do show up with an ordinary pictures card...

Is my inclusion of the module correct?

**Comment by badguy99** [comment]
If you've installed via HACS, it should have added the resource automatically. So you should see it under Configuration > Lovelace Dashboards > Resources
![image](https://user-images.githubusercontent.com/61918526/85235458-ec94bf80-b40c-11ea-9fe1-fe7351ceb44f.png)

So you shouldn't need to add the module any other way.

**Comment by filmgarage** [comment]
My Dashboards are configured through YAML, cannot add modules with the UI, so I added it to lovelace_setup.yaml
I guess that's part of the problem...

<img width="536" alt="Schermafbeelding 2020-06-21 om 23 31 45" src="https://user-images.githubusercontent.com/30559371/85235694-6c278c00-b417-11ea-850f-1a0ff58df0dd.png">

**Comment by badguy99** [comment]
I've never set anything up that way, sorry, so I'm not sure how it should all hang together when set up like that.

**Comment by filmgarage** [comment]
I will try and set it up on a test install without yaml dashboards. Just to know what's going on...
Thanks for your help!

**Comment by filmgarage** [comment]
I did find this in the log BTW:

```
Logger: frontend.js.latest.202006033
Source: components/system_log/__init__.py:209 
First occurred: 23:25:49 (3 occurrences) 
Last logged: 23:31:33

https://hass.url.com:8123/hacsfiles/PlantPictureCard/PlantPictureCard.js:81:47 TypeError: undefined is not an object (evaluating 'hass.states[String(_sensor)].attributes')
:0:0 Script error.
```

**Comment by badguy99** [comment]
ok, that's interesting. If you go to developer tools > states and filter one your plant, what do you have? I'm especially interested in the friendly name:

![image](https://user-images.githubusercontent.com/61918526/85236563-f1f70780-b416-11ea-8bc7-040108214651.png)

**Comment by filmgarage** [comment]
```
problem: brightness low, conductivity high
sensors: 
moisture: sensor.plant_john_name_moisture
temperature: sensor.plant_john_temperature
brightness: sensor.plant_john_illuminance
conductivity: sensor.plant_john_soil_conductivity

unit_of_measurement_dict: 
temperature: °C
moisture: '%'
brightness: lx
conductivity: µS/cm

moisture: 58
temperature: 25.3
brightness: 303
conductivity: 3218
max_brightness: 303
friendly_name: v5a_office_john_monstera
```

This plant does not have a 'battery' sensor...

**Comment by badguy99** [comment]
Right, I've found two ways to get it to blow up. One is get the entity plant.name wrong in lovelace config, and the other is probably what you are seeing - not having a sensor it is looking for - the battery sensor in your case - I will try and put in some protection for that.

**Comment by filmgarage** [comment]
Indeed, I added a 'dummy sensor' containing battery info and now it works...
