### ISSUE TITLE
Nice card, but need to change colors using CSS

### ISSUE THREAD

**Issue by DrJohnT** [badguy99/PlantPictureCard#2]
Here is my implementation.  As you can see, the text is completely lost on the background.  Is there anyway to customize the colors using CSS??  

![plant](https://user-images.githubusercontent.com/10464775/85329077-ba956300-b4c9-11ea-9a64-9a980ad4fca0.png)

**Comment by badguy99** [comment]
The unit of measurement row uses the variable --secondary-text-color and the icon uses the variable  --paper-item-icon-color so you should be able to use these in a theme to set the colours you would like.
