### ISSUE TITLE
Card is not displaying

### ISSUE THREAD

**Issue by bobvmierlo** [badguy99/PlantPictureCard#4]
The card is not displaying at all, seems to be related to the image.
However when I use the same image in the normal picture card it works fine.
The custom card is installed through HACS.

This is my lovelace card config:
```
type: 'custom:plant-picture-card'
entity: plant.plant1
title: Strelitzia
image: 'https://has.bobvmierlo.nl/local/strelitzia.png'
```

It shows nothing at all in the frontend. When using the same picture in a normal picture card it shows fine.

**Comment by badguy99** [comment]
what happens if you just put in a path:
```yaml
image: /local/strelitzia.png
```
instead of a web url?

**Comment by bobvmierlo** [comment]
Tried that, same problem

**Comment by bobvmierlo** [comment]
Hmm.. apparently it was some kind of browser cache issue. It's working now.
One other piece of feedback though, it seems like you have put the default picturecard image as a default background in your custom card. So if you input a png image without a background it puts the png on top of the default homeassistant tshirt picture.
See screenshot below:

![image](https://user-images.githubusercontent.com/38190383/86536658-971ae100-bee9-11ea-88f4-739c1780e52d.png)

**Comment by badguy99** [comment]
The conditional formatting is there..

```js
      if ( hass.states[config.entity].attributes.problem.indexOf(_sensors[parseInt(i)]) !== -1){
        _class += " state-problem";
      }
```

```css
      .state-problem {
        color: var(--google-red-500);
      }
```

I'll sort out the background picture issue.
