### ISSUE TITLE
The value doesn't change to red when state=problem

### ISSUE THREAD

**Issue by bobvmierlo** [badguy99/PlantPictureCard#6]
You stated in the issue before:
> The conditional formatting is there..
> 
> ```js
>       if ( hass.states[config.entity].attributes.problem.indexOf(_sensors[parseInt(i)]) !== -1){
>         _class += " state-problem";
>       }
> ```
> 
> ```css
>       .state-problem {
>         color: var(--google-red-500);
>       }
> ```

However this does not seem to work.
See screenshot:
![image](https://user-images.githubusercontent.com/38190383/86539750-62198900-beff-11ea-9b69-5be7be3d4718.png)

**Comment by bobvmierlo** [comment]
I think the problem is with the `color: var(--google-red-500);`
If I change the css in the chrome devtools to `color: #db4437;` it works fine.

**Comment by badguy99** [comment]
This is the same as the plant status card uses - https://github.com/iantrich/home-assistant-polymer/blob/ef18f9eac99dd8b5bc04fc1349ce4cde9f46c946/src/panels/lovelace/cards/hui-plant-status-card.ts#L194

**Comment by bobvmierlo** [comment]
Hmm.. that's weird. Since the default plant card works fine and shows red text, but your custom card doesn't show red text.
Also the default plant card shows `color: #db4437;` in the chrome devtools when checking the CSS from the default plantcard, so somewhere this gets converted from `color: var(--google-red-500);` to `color: #db4437;`

**Comment by badguy99** [comment]
![image](https://user-images.githubusercontent.com/61918526/86636135-d883bd00-bfcb-11ea-8e59-2fdd0fbc2056.png)

It works for me. I'm using the latest released version. The CSS var(--xxxxx) variables are converted in the Home Assistant themes.

**Comment by bobvmierlo** [comment]
Hmm weird, i'm fully updated with HassOS and HA Core. Still the text won't show as red.
I've fixed it for now by changing the code to the hex value.

**Comment by ec-blaster** [comment]
I have the same problem.
Latest HA Core 0.114.4 and any theme has the same problem...
