### ISSUE TITLE
Adding image doesn't show in preview etc

### ISSUE THREAD

**Issue by thefunkygibbon** [badguy99/PlantPictureCard#7]
So if i add this card and give it either the full http address or /local/image.jpg or png , it doesn't show in the preview to the right. 
If i save it, the whole of the 'view' is no longer visable. (have to go into the raw config and remove the card from there so the rest of the cards show up again.

using the normal picture card with the same addresses to the image work fine.

Tested on a few browsers so its not a cache thing. 

Any ideas? or has newer HA broken your integration?

**Comment by badguy99** [comment]
Works for me running core-2021.9.7

![ppc](https://user-images.githubusercontent.com/61918526/136286188-034bf4fd-8a29-4dbb-8f46-6ee8c0d17ce4.gif)

**Comment by ManuSwaG** [comment]
I have the exact same issue as the OP. Also adding the entity in the code editor makes the whole of the 'view' is no longer visable.

**Comment by almighty059** [comment]
@badguy99 @ManuSwaG I am having the same issue in core-2022.4.7.
